# Generated by Django 5.2.14 on 2026-07-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1247_oauthaccesstoken_token_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="duckgresserver",
            name="sink_max_concurrency",
            field=models.IntegerField(default=4),
        ),
    ]
