# Generated by Django 5.2.14 on 2026-07-07 00:42

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1248_duckgressinkschemastate_consecutive_failures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duckgresserver",
            name="sink_max_concurrency",
            field=models.IntegerField(default=4, validators=[MinValueValidator(1)]),
        ),
    ]
